#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

function run {
  CGO_ENABLED=0 go run main/main.go run --config example/Caddyfile "$@"
}

function build {
  CGO_ENABLED=0 go build -v -o caddy \
    -ldflags="-s -w" -trimpath -tags nobadger,nomysql,nopgx \
    main/main.go
}

function test {
  CGO_ENABLED=0 go test ./... -count 1 "$@"
}

function help {
  echo "$0 <task> <args>"
  echo "Tasks:"
  compgen -A function | grep -v "^_" | cat -n
}

"${@:-help}"

