#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

function run {
  CGO_ENABLED=0 go run main/main.go run --config example/Caddyfile "$@"
}

function build {
  CGO_ENABLED=0 go build -v -o caddy \
    -ldflags="-s -w" -trimpath -tags nobadger,nomysql,nopgx \
    main/main.go
}

function test {
  CGO_ENABLED=0 go test . "$@"
  speck
}

function speck {
  CGO_ENABLED=0 go run -C ./main . version > /dev/null
  VERBOSE=""
  if [ "$#" -ge 1 ] && [ "$1" == "-v" ]; then
    VERBOSE="-v"
    shift
  fi

  TESTS=$@
  if [ -z "$TESTS" ]; then
    TESTS=tests/*/_test.sh
  fi
  tests/speck.js $VERBOSE $TESTS
}

function help {
  echo "$0 <task> <args>"
  echo "Tasks:"
  compgen -A function | grep -v "^_" | cat -n
}

"${@:-help}"

