#!/usr/bin/env -S deno run -A

const PORT = Number(Deno.args[0]) ?? 8723;
const ANSWER = new Set(["/up", "/page"]);

Deno.serve({ port: PORT }, (req) => {
  const path = (new URL(req.url)).pathname;
  console.log(`Request path: "${path}" (${ANSWER.has(path)})`);

  if (!ANSWER.has(path)) {
    return new Response(null, { status: 515 });
  }

  const content = path == "/up"
    ? "UP"
    : Deno.readTextFileSync("." + path + ".md");

  return new Response(`SUBSTRATE
Request path: ${path}
X-Forwarded-Path: ${req.headers.get("x-forwarded-path")}
${content}
`);
});

