#!/usr/bin/env -S deno run -A

const PORT = 8723;
const SUB = Deno.env.get("SUBSTRATE") ?? "";
await fetch(SUB, {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    host: `:${PORT}`,
    match: ["*.md"],
    paths: ["/up"],
    catch_all: ["/all.md"],
  }),
});

Deno.serve({ port: PORT }, (req) => {
  const path = (new URL(req.url)).pathname;
  const content = path == "/up" ? "UP" : Deno.readTextFileSync("." + path);
  return new Response(`SUBSTRATE
Request path: ${path}
X-Forwarded-Path: ${req.headers.get("x-forwarded-path")}
${content}
`);
});

