#!/usr/bin/env -S deno run -A

const PORT = Number(Deno.args[0]) ?? 8723;
const ANSWER = new Set(["/up", "/page.md"]);

Deno.serve({ port: PORT }, (req) => {
  const path = (new URL(req.url)).pathname;
  console.log(`Request path: "${path}" (${ANSWER.has(path)})`);

  if (!ANSWER.has(path)) {
    return new Response(null, { status: 515 });
  }

  return new Response(`SUBSTRATE
Request path: ${req.url}
X-Forwarded-Path: ${req.headers.get("x-forwarded-path")}
`);
});

