#!/bin/sh
set -e

# if last argument is stop, consume it./
ACTION=""
if [ "$#" -ge 1 ] && [ "$1" == "stop" ]; then
  ACTION="stop"
  shift
fi

CADDYFILE="$1"
if [ -z "$CADDYFILE" ]; then
    CADDYFILE="./Caddyfile"
fi

CADDYFILE=$(realpath "$CADDYFILE")
export CWD=`pwd`


if [ "$ACTION" == "stop" ]; then
 CGO_ENABLED=0 go run -C ${DIR}/../main . stop --config $CADDYFILE 2>/dev/null || true
 exit 0
fi

CGO_ENABLED=0 go run -C ${DIR}/../main . start --config $CADDYFILE 2>/dev/null &

