#!/usr/bin/env -S deno run -A

const PORT = Number(Deno.args[0]) ?? 8723;
console.log("SUBSTRATE LISTENING ON", PORT);

Deno.serve({ port: PORT }, (req) => {
  const path = (new URL(req.url)).pathname;

  if (path == "/") {
    return new Response("", { status: 515 });
  }

  return new Response(`SUBSTRATE
Request path: ${path}
X-Forwarded-Path: ${req.headers.get("x-forwarded-path")}
`);
});

