#!/usr/bin/env -S deno run -A

const PORT = Number(Deno.args[0]) ?? 8723;

const ANSWER = new Set(["/up", "/page"]);

Deno.serve({ port: PORT }, (req) => {
  const path = (new URL(req.url)).pathname;

  if (!ANSWER.has(path)) {
    return new Response(null, { status: 515 });
  }

  const r = new Response(`SUBSTRATE
Request path: ${path}
X-Forwarded-Path: ${req.headers.get("x-forwarded-path")}
`);
  r.headers.set("x-substrate", "true");
  return r;
});

